title: 맥박의 블로그
email: pulsewings@gmail.com
description: |
  맥박의 일상 - 인생, 생활, 일기, 자전거, 수영
  일상의 일들을 돌이켜보고, 생각하고, 기록하면서, 나의 모습을 조금 더 알수 있을 것이라 믿습니다.
baseurl: ''
url: 'http://pulsewings.github.com'
timezone: Asia/Seoul

repository: pulsewings/pulsewings.github.com

permalink: /:year/:month/:day/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

gems:
  - jekyll-paginate
  - jemoji

paginate: 5
paginate_path: '/page/:num/'

collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]

keep_files: [assets, files]

# iolo's custom
author: opensource@kakaocorp.com
image: '/assets/images/default_blog_cover.jpg'
asset_url: /assets
#asset_url: //meta-kage.kakaocdn.net/dn/osa/blog/assets
#asset_url: //t1.daumcdn.net/osa/blog/assets
google_analytics:
  ua: ''
facebook:
  app_id: ''
  username: pulsewings
twitter:
  username: pulsewings
google_plus:
  username: pulsewings
github:
  username: pulsewings
